<script setup lang="ts">
import { Form, Head, Link } from '@inertiajs/vue3';
import { ref, watch } from 'vue';
import Heading from '@/components/Heading.vue';
import InputError from '@/components/InputError.vue';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';

const now = new Date();
const offset = now.getTimezoneOffset() * 60000;
const localISOTime = (new Date(now.getTime() - offset)).toISOString().slice(0, 16);
const activationDate = ref(localISOTime);
const selectedActivePreset = ref('now');

function setActivePreset(preset: string) {
    selectedActivePreset.value = preset;
    if (preset === 'now') {
        const current = new Date();
        const localOffset = current.getTimezoneOffset() * 60000;
        activationDate.value = (new Date(current.getTime() - localOffset)).toISOString().slice(0, 16);
    }
}

function handleActiveInput() {
    selectedActivePreset.value = 'custom';
}

function formatDateTime(val: string) {
    if (!val) return '';
    const d = new Date(val);
    if (isNaN(d.getTime())) return val;
    return d.toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' });
}

const expirationDate = ref('');
const selectedExpPreset = ref('year');

const balance = ref('20');
const selectedPreset = ref('20');

function setPreset(preset: string) {
    selectedPreset.value = preset;
    if (preset !== 'custom') {
        balance.value = preset;
    }
}

function handleBalanceInput() {
    selectedPreset.value = 'custom';
}

function setExpPreset(preset: string) {
    selectedExpPreset.value = preset;
    if (preset !== 'custom') {
        calculateExpirationDate();
    }
}

function handleExpInput() {
    selectedExpPreset.value = 'custom';
}

function calculateExpirationDate() {
    if (!activationDate.value || selectedExpPreset.value === 'custom') return;
    
    const baseDate = new Date(activationDate.value);
    if (isNaN(baseDate.getTime())) return;
    
    if (selectedExpPreset.value === '3m') {
        baseDate.setMonth(baseDate.getMonth() + 3);
    } else if (selectedExpPreset.value === '6m') {
        baseDate.setMonth(baseDate.getMonth() + 6);
    } else if (selectedExpPreset.value === '9m') {
        baseDate.setMonth(baseDate.getMonth() + 9);
    } else if (selectedExpPreset.value === 'year') {
        baseDate.setFullYear(baseDate.getFullYear() + 1);
    }
    
    const yyyy = baseDate.getFullYear();
    const mm = String(baseDate.getMonth() + 1).padStart(2, '0');
    const dd = String(baseDate.getDate()).padStart(2, '0');
    expirationDate.value = `${yyyy}-${mm}-${dd}`;
}

watch(activationDate, () => {
    if (selectedExpPreset.value !== 'custom') {
        calculateExpirationDate();
    }
});

calculateExpirationDate();

defineOptions({
    layout: {
        breadcrumbs: [
            {
                title: 'Gift Cards',
                href: '/cards',
            },
            {
                title: 'Create',
                href: '/cards/create',
            },
        ],
    },
});
</script>

<template>
    <Head title="Create Gift Card" />

    <div class="flex flex-col gap-6">
        <Heading title="Create Gift Card" description="Add a new gift card to the system" />

        <div class="rounded-xl border border-sidebar-border/70 p-6 dark:border-sidebar-border">
            <Form
                action="/cards"
                method="post"
                class="space-y-6"
                autocomplete="off"
                v-slot="{ errors, processing }"
            >
                <div class="grid gap-6 md:grid-cols-2">
                    <div class="col-span-1 md:col-span-2">
                        <div class="p-4 bg-muted/40 border border-sidebar-border/70 rounded-lg flex items-start gap-3">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="text-emerald-500 mt-0.5"><rect width="18" height="11" x="3" y="11" rx="2" ry="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/></svg>
                            <div>
                                <h4 class="text-sm font-semibold text-foreground">Zero-Knowledge Generation</h4>
                                <p class="text-sm text-muted-foreground mt-1">Card Number and PIN will be automatically and securely generated by the server upon creation. You will not have access to these raw values.</p>
                            </div>
                        </div>
                    </div>

                    <div class="flex flex-col gap-2">
                        <div class="flex items-center justify-between">
                            <Label for="activation_date">Activation Date</Label>
                            <div class="inline-flex items-center gap-0.5 p-0.5 bg-secondary/80 dark:bg-secondary/40 rounded-lg border border-input/40">
                                <button
                                    type="button"
                                    class="px-2.5 py-1 text-xs font-medium rounded-md transition-all duration-200"
                                    :class="selectedActivePreset === 'now' ? 'bg-background text-foreground shadow-sm' : 'text-muted-foreground hover:text-foreground'"
                                    @click="setActivePreset('now')"
                                >
                                    Now
                                </button>
                                <button
                                    type="button"
                                    class="px-2.5 py-1 text-xs font-medium rounded-md transition-all duration-200"
                                    :class="selectedActivePreset === 'custom' ? 'bg-background text-foreground shadow-sm' : 'text-muted-foreground hover:text-foreground'"
                                    @click="setActivePreset('custom')"
                                >
                                    Custom
                                </button>
                            </div>
                        </div>
                        <input type="hidden" name="activation_date" :value="activationDate" />
                        <Input
                            v-if="selectedActivePreset === 'custom'"
                            id="activation_date"
                            v-model="activationDate"
                            @input="handleActiveInput"
                            type="datetime-local"
                            required
                        />
                        <div v-else class="h-10 flex items-center px-3 text-sm font-medium text-muted-foreground bg-muted/40 rounded-md border border-input/30">
                            Active starting:&nbsp;<span class="text-foreground font-semibold">{{ formatDateTime(activationDate) }}</span>
                        </div>
                        <InputError :message="errors.activation_date" />
                    </div>

                    <div class="flex flex-col gap-2">
                        <div class="flex items-center justify-between">
                            <Label for="expiration_date">Expiration Date</Label>
                            <div class="inline-flex items-center gap-0.5 p-0.5 bg-secondary/80 dark:bg-secondary/40 rounded-lg border border-input/40">
                                <button
                                    type="button"
                                    class="px-2.5 py-1 text-xs font-medium rounded-md transition-all duration-200"
                                    :class="selectedExpPreset === '3m' ? 'bg-background text-foreground shadow-sm' : 'text-muted-foreground hover:text-foreground'"
                                    @click="setExpPreset('3m')"
                                >
                                    3M
                                </button>
                                <button
                                    type="button"
                                    class="px-2.5 py-1 text-xs font-medium rounded-md transition-all duration-200"
                                    :class="selectedExpPreset === '6m' ? 'bg-background text-foreground shadow-sm' : 'text-muted-foreground hover:text-foreground'"
                                    @click="setExpPreset('6m')"
                                >
                                    6M
                                </button>
                                <button
                                    type="button"
                                    class="px-2.5 py-1 text-xs font-medium rounded-md transition-all duration-200"
                                    :class="selectedExpPreset === '9m' ? 'bg-background text-foreground shadow-sm' : 'text-muted-foreground hover:text-foreground'"
                                    @click="setExpPreset('9m')"
                                >
                                    9M
                                </button>
                                <button
                                    type="button"
                                    class="px-2.5 py-1 text-xs font-medium rounded-md transition-all duration-200"
                                    :class="selectedExpPreset === 'year' ? 'bg-background text-foreground shadow-sm' : 'text-muted-foreground hover:text-foreground'"
                                    @click="setExpPreset('year')"
                                >
                                    1 Year
                                </button>
                                <button
                                    type="button"
                                    class="px-2.5 py-1 text-xs font-medium rounded-md transition-all duration-200"
                                    :class="selectedExpPreset === 'custom' ? 'bg-background text-foreground shadow-sm' : 'text-muted-foreground hover:text-foreground'"
                                    @click="setExpPreset('custom')"
                                >
                                    Custom
                                </button>
                            </div>
                        </div>
                        <input type="hidden" name="expiration_date" :value="expirationDate" />
                        <Input
                            v-if="selectedExpPreset === 'custom'"
                            id="expiration_date"
                            v-model="expirationDate"
                            @input="handleExpInput"
                            type="date"
                            required
                        />
                        <div v-else class="h-10 flex items-center px-3 text-sm font-medium text-muted-foreground bg-muted/40 rounded-md border border-input/30">
                            Expires on:&nbsp;<span class="text-foreground font-semibold">{{ expirationDate }}</span>
                        </div>
                        <InputError :message="errors.expiration_date" />
                    </div>

                    <div class="flex flex-col gap-2">
                        <div class="flex items-center justify-between">
                            <Label for="balance">Balance ($)</Label>
                            <div class="inline-flex items-center gap-0.5 p-0.5 bg-secondary/80 dark:bg-secondary/40 rounded-lg border border-input/40">
                                <button
                                    v-for="preset in ['5', '10', '20', '50']"
                                    :key="preset"
                                    type="button"
                                    class="px-2.5 py-1 text-xs font-medium rounded-md transition-all duration-200"
                                    :class="selectedPreset === preset ? 'bg-background text-foreground shadow-sm' : 'text-muted-foreground hover:text-foreground'"
                                    @click="setPreset(preset)"
                                >
                                    ${{ preset }}
                                </button>
                                <button
                                    type="button"
                                    class="px-2.5 py-1 text-xs font-medium rounded-md transition-all duration-200"
                                    :class="selectedPreset === 'custom' ? 'bg-background text-foreground shadow-sm' : 'text-muted-foreground hover:text-foreground'"
                                    @click="setPreset('custom')"
                                >
                                    Custom
                                </button>
                            </div>
                        </div>
                        <input type="hidden" name="balance" :value="balance" />
                        <Input
                            v-if="selectedPreset === 'custom'"
                            id="balance"
                            v-model="balance"
                            @input="handleBalanceInput"
                            type="number"
                            step="0.01"
                            min="0"
                            max="999999.99"
                            placeholder="0.00"
                            required
                        />
                        <div v-else class="h-10 flex items-center px-3 text-sm font-medium text-muted-foreground bg-muted/40 rounded-md border border-input/30">
                            Selected Balance:&nbsp;<span class="text-foreground font-semibold">${{ balance }}</span>
                        </div>
                        <InputError :message="errors.balance" />
                    </div>
                </div>

                <div class="flex items-center gap-4">
                    <Button :disabled="processing">Create Card</Button>
                    <Link href="/cards">
                        <Button type="button" variant="outline">Cancel</Button>
                    </Link>
                </div>
            </Form>
        </div>
    </div>
</template>
